### ISSUE TITLE
parseAlbumRawInfo return null

### ISSUE THREAD

**Issue by masterT** [masterT/bandcamp-scraper#16]
It looks like Bandcamp update their definition of the variable `TralbumData` in the `<script>` tag of the page. That makes the function `parseAlbumRawInfo` return `null` which fails the validation. Does anyone have an idea how to fix this? @soundofjw

**Comment by glenvollmer** [comment]
I just made a PR that will hopefully fix this bug!

**Comment by masterT** [comment]
Fixed in **version 1.2.1** 🎉
