### ISSUE TITLE
Fix search result schema json

### ISSUE THREAD

**Issue by JanneHarju** [masterT/bandcamp-scraper#31]
This is started to complain about wrong schema in search result schema. Problem is with oneOf it is now #/oneOf. So #/ must be moved from child object $ref to parent like this:
```
"#/oneOf": [
    { "$ref": "definitions/artist" },
    { "$ref": "definitions/album" },
    { "$ref": "definitions/track" },
    { "$ref": "definitions/fan" },
    { "$ref": "definitions/label" }
  ]
```

**Comment by masterT** [comment]
Hi, thanks for the notification, I fixed it and publish a new version `bandcamp-scraper@1.2.4`.
