### ISSUE TITLE
Search only for a particular type

### ISSUE THREAD

**Issue by kybradeck** [masterT/bandcamp-scraper#36]
Currently the `search` function returns all types of information. Is there a clean way to only search for one particular type—for example, albums?

**Comment by masterT** [comment]
Nope, I tried to do it but the Bandcamp website always return results of any type.

**Comment by kybradeck** [comment]
Okay, easy enough to filter out the responses once they're returned—thanks for the reply!

**Comment by masterT** [comment]
No problem! 🙂
