### ISSUE TITLE
Ability to get an album's tags

### ISSUE THREAD

**Issue by maxp-hover** [masterT/bandcamp-scraper#37]
This is a nice project, but I am surprised it doesn't include the tags from `getAlbumInfo`. It will probably not be that difficult to get it from the HTML page.

I will hopefully be submitting a PR for this in the near future.

**Comment by maxp-hover** [comment]
PR submitted https://github.com/masterT/bandcamp-scraper/pull/38

**Comment by masterT** [comment]
I just published `bandcamp-scraper@1.2.5`. 🎉
