### ISSUE TITLE
Issue with Webpack

### ISSUE THREAD

**Issue by tyleragnew** [masterT/bandcamp-scraper#39]
First off, thank you for creating this repo!! I am excited to use it. I brought it into a project and I am seeing the following errors:

./node_modules/bandcamp-scraper/node_modules/ajv/lib/async.js
Critical dependency: the request of a dependency is an expression

./node_modules/bandcamp-scraper/node_modules/ajv/lib/async.js
Critical dependency: the request of a dependency is an expression

./node_modules/bandcamp-scraper/node_modules/ajv/lib/compile/index.js
Critical dependency: the request of a dependency is an expression

Can you recreate this error in a webpack project? It looks like its related to ajv:
https://stackoverflow.com/questions/42908116/webpack-critical-dependency-the-request-of-a-dependency-is-an-expression

FYI, I have already reset my npm cache

**Comment by masterT** [comment]
Hi @tyleragnew 

This project is meant to be used on the server-side, not the client-side, I don't think you can have `request` on the client-side.

**Comment by tyleragnew** [comment]
Gotcha - thanks @masterT - ill wrap this in a service.
