### ISSUE TITLE
Relative Module not Found - Cheerio.js

### ISSUE THREAD

**Issue by knightspore** [masterT/bandcamp-scraper#45]
I've got a gridsome (vue) project where I'm trying to use the bandcamp scraper and I'm getting the following error:

```
ERROR  Failed to compile with 2 errors                                      16:27:13

This relative module was not found:

* ./package in ./node_modules/cheerio-req/node_modules/cheerio/index.js, ./node_modules/scrape-it/node_modules/cheerio/index.js
```
I've tried a few different fixes but I'm still learning and I feel like I'm missing something obvious

**Comment by masterT** [comment]
This package is meant to be used by a backend server, not by a frontend application directly.

**Comment by knightspore** [comment]
Thanks for the explanation, I didn't realise!
