### ISSUE TITLE
getAlbumInfo bug with "preview" albums

### ISSUE THREAD

**Issue by Seizeweb** [masterT/bandcamp-scraper#50]
Hi !

I think I might have found a bug, when trying to retrieve infos from a release that is in "preview" on BC (ie: when the whole tracklist is available, but only a couple tracks are actually playable).

I tried with 3 releases, and I seem to get the same error for all 3 of them : 
`Validation error on album info:  data.tracks[0] should have required property 'name'`

Here are the 3 example releases if you want to check out for yourself (bear in mind, that based on when you check out these links, these releases might be out and not be in "preview" anymore) : 
https://lobstertheremin.com/album/girl-like-me-ep
https://venusexmachina.com/album/lux
https://biosphere.bandcamp.com/album/angels-flight

Whereas it works perfectly for all "non-preview" releases.

PS: if indeed this is something you'd like fixed, I'm happy to have a go at contributing.

**Comment by Seizeweb** [comment]
Ok so I just checked, I might have found what is creating the issue : these non-playable tracks don't have the class `track-title` on the `span`, causing a problem in the htmlParser.

If I find time I might submit a PR, should you want to add support for these non-playable tracks.

**Comment by masterT** [comment]
Fixed in PR #52.

**Comment by masterT** [comment]
Version `bandcamp-scraper@1.2.10` published.
