### ISSUE TITLE
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ... (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

### ISSUE THREAD

**Issue by shaenr** [masterT/bandcamp-scraper#58]
Is it possible to pass in some kind of headers object that would make this work or is the server just configured to deny requests?

**Comment by shaenr** [comment]
I'm an idiot. It seems to work if im not running the code from a react development server on localhost. So i guess i can at least get the info in node if not use it in browser app ?

**Comment by masterT** [comment]
Currently this package is only made to be used in on the server side.
