### ISSUE TITLE
Wish there was a way to get a more comprehensive list of labels

### ISSUE THREAD

**Issue by MaxPleaner** [masterT/bandcamp-scraper#8]
I'm using this tool to try and build an index of labels on bandcamp, sorted by genre.

I have a script that takes a query ("metal") and paginates through the results until they're empty, selecting only those that are labels. The problem is that it only finds 8 or so results - all in the first 2 pages, and there are only 6 total pages of results.

I don't think this is a flaw in your tool in as much as bandcamp doesn't offer this functionality. But I cannot imagine any reason they would not want to do this. It seems so obvious that there should be a categorized list of labels, but there isn't. 

I would be open to contributing some code if you can think of a way to achieve this. Or if you have any hunches that would be appreciated too.

**Comment by MaxPleaner** [comment]
Here's the thing I made fwiw: https://maxpleaner.github.io/bandcamp_labels

**Comment by masterT** [comment]
Hi! 

I wish there was a way to fetch any result grouped by its kind but _Bandcamp_ don't offer this feature, at least that I am aware of on there web application.

I know they have an [iOS app](https://itunes.apple.com/us/app/bandcamp/id706408639?ls=1&mt=8) and [Android app](https://play.google.com/store/apps/details?id=com.bandcamp.android), I did not investigate what request are made from those. Maybe we should start from there.

**Comment by masterT** [comment]
You can't search by label on the Android app neither. 😞

**Comment by monochord** [comment]
Not sure if it helps, but they seem to have a sort of artist/label index on their site:
https://bandcamp.com/artist_index
