### ISSUE TITLE
Search doesn't work in my app

### ISSUE THREAD

**Issue by JanneHarju** [masterT/bandcamp-scraper#9]
Can you check what might be wrong in my test? https://github.com/JanneHarju/MultiSourcePlayList/blob/master/angular2App/app/modules/searchlist/searchlist.component.ts#L58

**Comment by JanneHarju** [comment]
Sorry. Now its working. Thank you for this great workaround.

**Comment by JanneHarju** [comment]
Sorry for spam I just think that it worked but it was my test print. So still this is not working. it doesn't return a thing.

**Comment by JanneHarju** [comment]
It works here https://npm.runkit.com/bandcamp-scraper but for some reason callbacks never occure.

**Comment by masterT** [comment]
hi there, the scraper is working fine, I just ran your code ([I made a gist](https://gist.github.com/masterT/782ae52876d73dd9c007d16eef71b93f)). The problem might be somewhere else in your code. I don't know Angular at all, I can't help you with that. 😞

**Comment by JanneHarju** [comment]
That's what I was worried about. But thanks anyway. Great workaround for bandcamp.

**Comment by FranzSkuffka** [comment]
I think that it's not possible to use the scraper from the fronted. You will have to run it on the server and share the results with the client.

**Comment by JanneHarju** [comment]
Hmm. I was think of that, but I didn''t have time to test it. My problem will be how to use it with .NET Core. How can I use javascript in C#. Or is this ment to use with node.js server or such? I think that maybe I can make that http call from backend and then forward result to your htmlParser.parseSearchResults(res); method.
